**Imports**

In [ ]:
pip install GEKKO

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 80.2 MB/s eta 0:00:00


In [ ]:
from gekko import GEKKO
from numpy import *

##Qn1.1

In [ ]:
# Create a GEKKO model
m = GEKKO(remote=False)

# Coefficients for the linear objective function
c = array([[-9.0], [-5.0], [-6.0], [-4.0]])

# Coefficients for the inequality constraints (Ax <= b)
A = array([[-6, -3, -5, -2], [-1, 0, 0, -1], [1, 0, -1, 0], [0, 1, 0, -1]])
b = array([[-10], [-1], [0], [0]])

# Define binary decision variables
x1 = m.Var(1, integer=True, lb=0, ub=1)
x2 = m.Var(1, integer=True, lb=0, ub=1)
x3 = m.Var(1, integer=True, lb=0, ub=1)
x4 = m.Var(1, integer=True, lb=0, ub=1)

# Collect decision variables into a list
z = [x1, x2, x3, x4]

# Set up the objective function (maximize)
m.qobj(c, x=z, otype='min')

# Set up the inequality constraints (Ax >= b)
m.axb(A, b, x=z, etype='>=')

# Set the solver option to use APOPT (IPOPT is also available)
m.options.SOLVER = 1

# Solve the optimization problem
m.solve()

# Display the results
print('Objective: ', m.options.OBJFCNVAL)
print('Optimal Solution:')
print('x1 =', int(x1.value[0]))
print('x2 =', int(x2.value[0]))
print('x3 =', int(x3.value[0]))
print('x4 =', int(x4.value[0]))

A
[[-6. -3. -5. -2.]
 [-1.  0.  0. -1.]
 [ 1.  0. -1.  0.]
 [ 0.  1.  0. -1.]]
b
[[-10.  -1.   0.   0.]]
 ----------------------------------------------------------------
 APMonitor, Version 1.0.1
 APMonitor Optimization Suite
 ----------------------------------------------------------------
 
 
 --------- APM Model Size ------------
 Each time step contains
   Objects      :            2
   Constants    :            0
   Variables    :            4
   Intermediates:            0
   Connections  :            8
   Equations    :            0
   Residuals    :            0
 
 Number of state variables:              4
 Number of total equations: -            4
 Number of slack variables: -            0
 ---------------------------------------
 Degrees of freedom       :              0
 
 ----------------------------------------------
 Steady State Optimization with APOPT Solver
 ----------------------------------------------
Iter:     1 I:  0 Tm:      0.00 NLPi:    2 Dpth:    0 Lvs:    2 

##Qn1.2

In [ ]:
# Create a GEKKO model
m = GEKKO(remote=False)

# Coefficients for the linear objective function
c = array([[-7.0], [-3.0]])

# Coefficients for the inequality constraints (Ax <= b)
A = array([[-5, -7], [-4, -1], [-3, 2]])
b = array([[-27], [-14], [-9]])

# Define binary and continuous decision variables
x1 = m.Var(1, integer=True, lb=0)
x2 = m.Var(1, integer=False, lb=0)

# Collect decision variables into a list
z = [x1, x2]

# Set up the objective function (maximize)
m.qobj(c, x=z, otype='min')

# Set up the inequality constraints (Ax <= b)
m.axb(A, b, x=z, etype='>=')

# Set the solver option to use APOPT (IPOPT is also available)
m.options.SOLVER = 1

# Solve the optimization problem
m.solve()

# Display the results
print('Objective: ', m.options.OBJFCNVAL)
print('Optimal Solution:')
print('x1 =', int(x1.value[0]))
print('x2 =', int(x2.value[0]))

A
[[-5. -7.]
 [-4. -1.]
 [-3.  2.]]
b
[[-27. -14.  -9.]]
 ----------------------------------------------------------------
 APMonitor, Version 1.0.1
 APMonitor Optimization Suite
 ----------------------------------------------------------------
 
 
 --------- APM Model Size ------------
 Each time step contains
   Objects      :            2
   Constants    :            0
   Variables    :            2
   Intermediates:            0
   Connections  :            4
   Equations    :            0
   Residuals    :            0
 
 Number of state variables:              2
 Number of total equations: -            3
 Number of slack variables: -            0
 ---------------------------------------
 Degrees of freedom       :             -1
 
 * Warning: DOF <= 0
 ----------------------------------------------
 Steady State Optimization with APOPT Solver
 ----------------------------------------------
Iter:     1 I:  0 Tm:      0.00 NLPi:    2 Dpth:    0 Lvs:    2 Obj: -2.66E+01 Gap:       N

##Qn1.3

In [ ]:
# Create a GEKKO model
m = GEKKO(remote=False)

# Coefficients for the linear objective function
c = array([[1.0], [1.0]])

# Coefficients for the inequality constraints (Ax <= b)
A = array([[3, -2], [8, -10]])
b = array([[1], [-10]])

# Define continuous and binary decision variables
x1 = m.Var(1, integer=False, lb=0.3)
x2 = m.Var(1, integer=True, lb=0, ub=1)

# Collect decision variables into a list
z = [x1, x2]

# Set up the objective function (minimize)
m.qobj(c, x=z, otype='min')

# Set up the inequality constraints (Ax <= b)
m.axb(A, b, x=z, etype='>=')

# Set the solver option to use APOPT (IPOPT is also available)
m.options.SOLVER = 1

# Solve the optimization problem
m.solve()

# Display the results
print('Objective: ', m.options.OBJFCNVAL)
print('Optimal Solution:')
print('x1 =', x1.value[0])
print('x2 =', int(x2.value[0]))

A
[[  3.  -2.]
 [  8. -10.]]
b
[[  1. -10.]]
 ----------------------------------------------------------------
 APMonitor, Version 1.0.1
 APMonitor Optimization Suite
 ----------------------------------------------------------------
 
 
 --------- APM Model Size ------------
 Each time step contains
   Objects      :            2
   Constants    :            0
   Variables    :            2
   Intermediates:            0
   Connections  :            4
   Equations    :            0
   Residuals    :            0
 
 Number of state variables:              2
 Number of total equations: -            2
 Number of slack variables: -            0
 ---------------------------------------
 Degrees of freedom       :              0
 
 ----------------------------------------------
 Steady State Optimization with APOPT Solver
 ----------------------------------------------
Iter:     1 I:  0 Tm:      0.00 NLPi:    1 Dpth:    0 Lvs:    0 Obj:  3.33E-01 Gap:  0.00E+00
 Successful solution
 
 ------

##Qn1.4

In [ ]:
# Create a GEKKO model
m = GEKKO(remote=False)

# Coefficients for the linear objective function
c = array([[-120.0], [-85.0], [-105.0], [-140.0], [-70.0]])

# Coefficients for the inequality constraints (Ax <= b)
A = array([[-55, -45, -60, -50, -30], [-40, -35, -25, -35, -30], [-25, -20, -0, -30, -0]])
b = array([[-150], [-110], [-60]])

# Define binary decision variables
x1 = m.Var(1, integer=True, lb=0, ub=1)
x2 = m.Var(1, integer=True, lb=0, ub=1)
x3 = m.Var(1, integer=True, lb=0, ub=1)
x4 = m.Var(1, integer=True, lb=0, ub=1)
x5 = m.Var(1, integer=True, lb=0, ub=1)

# Collect decision variables into a list
z = [x1, x2, x3, x4, x5]

# Set up the objective function (maximize)
m.qobj(c, x=z, otype='min')

# Set up the inequality constraints (Ax <= b)
m.axb(A, b, x=z, etype='>=')

# Set the solver option to use APOPT (IPOPT is also available)
m.options.SOLVER = 1

# Solve the optimization problem
m.solve()

# Display the results
print('Objective: ', m.options.OBJFCNVAL)
print('Optimal Solution:')
print('x1 =', int(x1.value[0]))
print('x2 =', int(x2.value[0]))
print('x3 =', int(x3.value[0]))
print('x4 =', int(x4.value[0]))
print('x5 =', int(x5.value[0]))

A
[[-55. -45. -60. -50. -30.]
 [-40. -35. -25. -35. -30.]
 [-25. -20.   0. -30.   0.]]
b
[[-150. -110.  -60.]]
 ----------------------------------------------------------------
 APMonitor, Version 1.0.1
 APMonitor Optimization Suite
 ----------------------------------------------------------------
 
 
 --------- APM Model Size ------------
 Each time step contains
   Objects      :            2
   Constants    :            0
   Variables    :            5
   Intermediates:            0
   Connections  :           10
   Equations    :            0
   Residuals    :            0
 
 Number of state variables:              5
 Number of total equations: -            3
 Number of slack variables: -            0
 ---------------------------------------
 Degrees of freedom       :              2
 
 ----------------------------------------------
 Steady State Optimization with APOPT Solver
 ----------------------------------------------
Iter:     1 I:  0 Tm:      0.00 NLPi:    2 Dpth:    0 Lvs: